# Generated by Django 2.2.6 on 2019-11-01 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20191031_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10, verbose_name='链接标题')),
                ('href', models.CharField(max_length=255, verbose_name='链接地址')),
                ('index', models.IntegerField(default=999, verbose_name='排序')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
            },
        ),
    ]
