# Generated by Django 2.2.6 on 2019-11-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='isLink',
            field=models.BooleanField(default=False, verbose_name='显示在导航栏'),
        ),
    ]
