# Generated by Django 2.2.6 on 2019-11-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_catagory_islink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catagory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='分类名称'),
        ),
    ]
